set(_CATKIN_CURRENT_PACKAGE "robo_team_charlie")
set(robo_team_charlie_VERSION "0.0.0")
set(robo_team_charlie_MAINTAINER "nick <nick@todo.todo>")
set(robo_team_charlie_PACKAGE_FORMAT "1")
set(robo_team_charlie_BUILD_DEPENDS )
set(robo_team_charlie_BUILD_EXPORT_DEPENDS )
set(robo_team_charlie_BUILDTOOL_DEPENDS "catkin")
set(robo_team_charlie_BUILDTOOL_EXPORT_DEPENDS )
set(robo_team_charlie_EXEC_DEPENDS )
set(robo_team_charlie_RUN_DEPENDS )
set(robo_team_charlie_TEST_DEPENDS )
set(robo_team_charlie_DOC_DEPENDS )
set(robo_team_charlie_DEPRECATED "")